# Generated by Django 4.2 on 2025-09-06 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppit', '0007_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile_image/blank.png', upload_to='profile-image'),
        ),
    ]
